2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Configure stats pid to 438
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from /Users/saahil/.config/wandb/settings
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/settings
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 22:47:36,018 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 22:47:36,018 ERROR   MainThread:438 [wandb_setup.py:_flush():78] error in wandb.init()
Traceback (most recent call last):
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/n_/4p37f261177fmjpv4kt7x33m0000gn/T/ipykernel_438/868237815.py", line 1, in <module>
    wandb.init(project="yoga_pose_classification", config={"epochs": 10, "batch_size": 32, "image_size": (256, 256)})
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    wandb._sentry.reraise(e)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    wi.setup(kwargs)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 300, in setup
    wandb_login._login(
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 340, in _login
    wlogin.prompt_api_key()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 270, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 249, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-06-29 22:47:36,041 INFO    MainThread:438 [wandb_init.py:_log_setup():520] Logging user logs to /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/offline-run-20240629_224736-ejdr2jhc/logs/debug.log
2024-06-29 22:47:36,041 INFO    MainThread:438 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/offline-run-20240629_224736-ejdr2jhc/logs/debug-internal.log
2024-06-29 22:47:36,041 INFO    MainThread:438 [wandb_init.py:init():560] calling init triggers
2024-06-29 22:47:36,041 INFO    MainThread:438 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch_size': 32, 'image_size': (256, 256), 'learning_rate': 0.001, 'optimizer': 'adam'}
2024-06-29 22:47:36,041 INFO    MainThread:438 [wandb_init.py:init():610] starting backend
2024-06-29 22:47:36,041 INFO    MainThread:438 [wandb_init.py:init():614] setting up manager
2024-06-29 22:47:36,042 INFO    MainThread:438 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-29 22:47:36,042 INFO    MainThread:438 [wandb_init.py:init():622] backend started and connected
2024-06-29 22:47:36,044 INFO    MainThread:438 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-29 22:47:36,044 INFO    MainThread:438 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-29 22:47:36,044 INFO    MainThread:438 [wandb_init.py:init():711] updated telemetry
2024-06-29 22:47:36,044 INFO    MainThread:438 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-29 22:49:06,396 ERROR   MainThread:438 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-29 22:49:06,400 ERROR   MainThread:438 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-29 22:49:40,465 INFO    MainThread:438 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Configure stats pid to 438
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from /Users/saahil/.config/wandb/settings
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/settings
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 22:49:40,467 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 22:49:40,467 ERROR   MainThread:438 [wandb_setup.py:_flush():78] error in wandb.init()
Traceback (most recent call last):
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/n_/4p37f261177fmjpv4kt7x33m0000gn/T/ipykernel_438/868237815.py", line 1, in <module>
    wandb.init(project="yoga_pose_classification", config={"epochs": 10, "batch_size": 32, "image_size": (256, 256)})
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    wandb._sentry.reraise(e)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    wi.setup(kwargs)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 300, in setup
    wandb_login._login(
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 340, in _login
    wlogin.prompt_api_key()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 270, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 249, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-06-29 22:49:40,503 INFO    MainThread:438 [wandb_init.py:_log_setup():520] Logging user logs to /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/offline-run-20240629_224940-ztcztk6e/logs/debug.log
2024-06-29 22:49:40,503 INFO    MainThread:438 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/offline-run-20240629_224940-ztcztk6e/logs/debug-internal.log
2024-06-29 22:49:40,503 INFO    MainThread:438 [wandb_init.py:init():560] calling init triggers
2024-06-29 22:49:40,503 INFO    MainThread:438 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch_size': 32, 'image_size': (256, 256), 'learning_rate': 0.001, 'optimizer': 'adam'}
2024-06-29 22:49:40,504 INFO    MainThread:438 [wandb_init.py:init():610] starting backend
2024-06-29 22:49:40,504 INFO    MainThread:438 [wandb_init.py:init():614] setting up manager
2024-06-29 22:49:40,504 INFO    MainThread:438 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-06-29 22:49:40,505 INFO    MainThread:438 [wandb_init.py:init():622] backend started and connected
2024-06-29 22:49:40,507 INFO    MainThread:438 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-29 22:49:40,507 INFO    MainThread:438 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-29 22:49:40,507 INFO    MainThread:438 [wandb_init.py:init():711] updated telemetry
2024-06-29 22:49:40,507 INFO    MainThread:438 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-29 22:51:10,860 ERROR   MainThread:438 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-29 22:51:10,866 ERROR   MainThread:438 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-29 22:51:44,137 INFO    MainThread:438 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2024-06-29 22:51:44,139 INFO    MainThread:438 [wandb_setup.py:_flush():76] Configure stats pid to 438
2024-06-29 22:51:44,139 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from /Users/saahil/.config/wandb/settings
2024-06-29 22:51:44,139 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/settings
2024-06-29 22:51:44,139 INFO    MainThread:438 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-06-29 22:51:44,140 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-06-29 22:51:44,140 INFO    MainThread:438 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-06-29 22:51:44,140 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 22:51:44,140 INFO    MainThread:438 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-06-29 22:51:44,140 ERROR   MainThread:438 [wandb_setup.py:_flush():78] error in wandb.init()
Traceback (most recent call last):
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/n_/4p37f261177fmjpv4kt7x33m0000gn/T/ipykernel_438/868237815.py", line 1, in <module>
    wandb.init(project="yoga_pose_classification", config={"epochs": 10, "batch_size": 32, "image_size": (256, 256)})
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    wandb._sentry.reraise(e)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    wi.setup(kwargs)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 300, in setup
    wandb_login._login(
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 340, in _login
    wlogin.prompt_api_key()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 270, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 249, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-06-29 22:51:44,152 INFO    MainThread:438 [wandb_init.py:_log_setup():520] Logging user logs to /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/offline-run-20240629_225144-ug73is4i/logs/debug.log
2024-06-29 22:51:44,152 INFO    MainThread:438 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/wandb/offline-run-20240629_225144-ug73is4i/logs/debug-internal.log
2024-06-29 22:51:44,152 INFO    MainThread:438 [wandb_init.py:init():560] calling init triggers
2024-06-29 22:51:44,152 INFO    MainThread:438 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch_size': 32, 'image_size': (256, 256), 'learning_rate': 0.001, 'optimizer': 'adam'}
2024-06-29 22:51:44,152 INFO    MainThread:438 [wandb_init.py:init():610] starting backend
2024-06-29 22:51:44,152 INFO    MainThread:438 [wandb_init.py:init():614] setting up manager
2024-06-29 22:51:44,153 INFO    MainThread:438 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: fork
2024-06-29 22:51:44,153 INFO    MainThread:438 [wandb_init.py:init():622] backend started and connected
2024-06-29 22:51:44,155 INFO    MainThread:438 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-06-29 22:51:44,155 INFO    MainThread:438 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-06-29 22:51:44,155 INFO    MainThread:438 [wandb_init.py:init():711] updated telemetry
2024-06-29 22:51:44,155 INFO    MainThread:438 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-06-29 22:53:14,483 ERROR   MainThread:438 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-06-29 22:53:14,487 ERROR   MainThread:438 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/Users/saahil/Desktop/Coding_Projects/DL/PoseYoga TL/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
